Month 9/step 1
AntonKarpukhin/react-stellar-burger pull request #7
Opened 2023-07-03 18:34 UTC by AntonKarpukhin

Промежуточное ревью. Итерация 1.

2023-07-03 19:19 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали обновление токена
- Настроены все редиректы
- Защита роутов находится в одном компоненте 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- в запрос по ресету пароля не попадает токен из письма. 

![Снимок экрана 2023-07-03 в 22 13 14](https://github.com/AntonKarpukhin/react-stellar-burger/assets/60173362/fd745dd4-0f84-45cb-973d-cdb988cf6af9)

- в payload patch запроса на изменение данных юзера не попадает пароль
- Обновление токена не работает из-за того, что в хедер запроса попадает два токена сразу. Это баг. Связан он с тем, что `authorization` в коде где-то пишется с заглавной, а где-то со строчной.
- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.


**Можно лучше**
- Запрос регистрации возвращает ответом токены и данные юзера, поэтому его можно сразу авторизовать.
- Лого хедера лучше сделать ссылкой на главную страницу
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью ` return <Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate`)


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-03 19:19 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                <Route path="/register" element={<OnlyUnAuth component={<Registration/>}/>}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-03 19:19 UTC, andryxxa93 commented on src/pages/profile/profile.jsx
> +    const onChangeEmail = e => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-07-03 19:43 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-03 21:49 UTC, AntonKarpukhin commented
> Супер, вы отлично поработали! Поздравляю! Работа принята. Желаю удачного продолжения обучения!

Рановато, еще проверить надо ))
Это не понял как сделать ((
Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return <Navigate to={location?.state?.from || '/'} />; (эти данные записываются в ProtectedRoute, а используются в Login для Navigate)

2023-07-04 07:21 UTC, andryxxa93 commented
> > Супер, вы отлично поработали! Поздравляю! Работа принята. Желаю удачного продолжения обучения!
> 
> Рановато, еще проверить надо )) Это не понял как сделать (( Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью return <Navigate to={location?.state?.from || '/'} />; (эти данные записываются в ProtectedRoute, а используются в Login для Navigate)

    ```
const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
```

2023-07-04 07:22 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-04 19:40 UTC, merged